# Book settings
title: Continuous Time Markov Chains
author: John Stachurski
# logo: logo.png

sphinx:
  config:
    myst_override_mathjax: false
    mathjax_config:
      TeX:
        Macros:
          "Exp" : ["\\operatorname{Exp}"]
          "BB" : ["\\mathbb{B}"]
          "EE" : ["\\mathbb{E}"]
          "PP" : ["\\mathbb{P}"]
          "RR" : ["\\mathbb{R}"]
          "NN" : ["\\mathbb{N}"]
          "ZZ" : ["\\mathbb{Z}"]

latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
